#!/usr/bin/env python3

import urllib.request
import urllib.parse
import json
import re
import sys
import datetime

import feedgenerator

session_cookie = "sessionid=" + sys.argv[1]
ig_regex = re.escape('<script type="text/javascript">window._sharedData = ') + r'(\{.*\})' +re.escape(';</script>')
ig_url = "https://www.instagram.com"

# Prevents image url from changing
def cdn_fix(url):
    url = re.sub(r'https://scontent-.*\.cdninstagram.com', 'https://scontent.cdninstagram.com', url)
    scheme, netloc, path, _, _ = urllib.parse.urlsplit(url)
    url = scheme + '://' + netloc + path
    return url

opener = urllib.request.build_opener()
opener.addheaders.append(('Cookie', session_cookie))

page = opener.open(ig_url).read().decode()

m = re.search(ig_regex, page)
sharedData = json.loads(m.group(1))

#print(sharedData['entry_data']['FeedPage'][0]['suggestedUsersList'])
media = sharedData['entry_data']['FeedPage'][0]['feed']['media']
#page_info = media['page_info']

feed = feedgenerator.Atom1Feed("Instagram", ig_url, "")

for i in media['nodes']:
    id_ = i['id']

    location = i['location']
    location_link = ''
    if location:
        location_url = ig_url + "/explore/locations/" + location['id']
        location_link = '<p>Location: <a href="' + location_url + '">' + location['name'] + r'<\a><\p>'

    tagged = [j['user']['username'] for j in i['usertags']['nodes']]
    tagged_html = ''
    if tagged:
        tagged_links = ['<a href="' + ig_url + '/' + j + '">' + j + r'<\a>' for j in tagged]
        tagged_html = '<p> Tagged: ' + ', '.join(tagged_links) + r'<\p>'

    src = cdn_fix(i['display_src'])
    video_url = i.get('video_url')
    if video_url:
        video_url = cdn_fix(video_url)
    url = video_url or src

    username = i['owner']['username']
    full_name = i['owner']['full_name'] or ''
    profile_pic_url = cdn_fix(i['owner']['profile_pic_url'])
    user_url = ig_url + "/" + username
    author = username
    if full_name:
        author += ' (' + full_name + ')'

    caption = i.get('caption', '')
    date = datetime.datetime.fromtimestamp(i['date'])

    title = username + ': ' + caption
    #if len(caption) > 50: # Arbitrarily chosen number
    #    title = title[:47] + '...'

    img = '<p><img src="' + src + '"/></p>'
    content = location_link + tagged_html + img + '<p>'+ caption + '<\p>'

    feed.add_item(title, url, caption, author_name=author, author_link=user_url, pubdate=date, content=content, unique_id='instagram:'+id_)

print(feed.writeString('utf8'))
