#!/usr/bin/env python3

import urllib.request
import urllib.parse
import json
import re
import sys
import datetime

import feedgenerator

session_cookie = "sessionid=" + sys.argv[1]
ig_regex = re.escape('<script type="text/javascript">window.__additionalDataLoaded(\'feed\',') + r'(\{.*\})' +re.escape(');</script>')


ig_url = "https://www.instagram.com"

# Prevents image url from changing
def cdn_fix(url):
    #scheme, netloc, path, _, _ = urllib.parse.urlsplit(url)
    #netloc = re.sub(r'scontent-.*\.cdninstagram\.com', 'scontent.cdninstagram.com', netloc)
    #url = scheme + '://' + netloc + path
    return url

opener = urllib.request.build_opener()
opener.addheaders.append(('Cookie', session_cookie))

page = opener.open(ig_url).read().decode()

m = re.search(ig_regex, page)
ig_feed = json.loads(m.group(1))

feed = feedgenerator.Atom1Feed("Instagram", ig_url, "")

def process_graphimage(i):
    if not 'owner' in i:
        return

    id_ = i['id']

    location = i['location']
    location_link = ''
    if location:
        location_url = ig_url + "/explore/locations/" + location['id']
        location_link = f'<p>Location: <a href="{location_url}">{location["name"]}</a></p>'

    tagged = (j['node']['user']['username'] for j in i['edge_media_to_tagged_user']['edges'])
    tagged_html = ''
    if tagged:
        tagged_links = [f'<a href="{ig_url}/{j}">{j}</a>' for j in tagged]
        tagged_html = '<p> Tagged: ' + ', '.join(tagged_links) + r'</p>'

    url = i['display_url']
    imgs = ''
    if 'edge_sidecar_to_children' in i:
        for j in i['edge_sidecar_to_children']['edges']:
            j_url = j['node']['display_url']
            imgs += f'<p><img src="{j_url}"/></p>'
    else:
        imgs = f'<p><img src="{url}"/></p>'
    #video_url = i.get('video_url') TODO

    username = i['owner']['username']
    full_name = i['owner']['full_name'] or ''
    profile_pic_url = cdn_fix(i['owner']['profile_pic_url'])
    user_url = ig_url + "/" + username
    author = username
    if full_name:
        author += ' (' + full_name + ')'

    caption = i["edge_media_to_caption"]["edges"][0]["node"]["text"]
    date = datetime.datetime.fromtimestamp(i['taken_at_timestamp'])

    title = username + ': '
    #if video_url:
    #    title += '[video] '
    title += caption
    #if len(caption) > 50: # Arbitrarily chosen number
    #    title = title[:47] + '...'

    content = location_link + tagged_html + imgs + '<p>'+ caption + '</p>'

    feed.add_item(title, url, caption, author_name=author, author_link=user_url, pubdate=date, content=content, unique_id='instagram:'+id_)

def process_edges(edges):
    for i in edges:
        node = i['node']
        if node['__typename'] in ('GraphImage', 'GraphSidecar'):
            process_graphimage(node)

process_edges(ig_feed["user"]["edge_web_feed_timeline"]["edges"])

print(feed.writeString('utf8'))
